### ISSUE TITLE
老铁 银天下怎么样啊

### ISSUE THREAD

**Issue by RisonGao** [DefaultYuan/Git-Pro#1]
在网上查 有很多人在黑这个公司。。。我在考虑能不能过去发展。在这里发问题 请见谅。。谢谢。
如果不方便回答，可以删除该问题

**Comment by defaultyuan** [comment]
挺轻松的，不加班，福利好！

**Comment by RisonGao** [comment]
能加个QQ么 有些问题不方便网上讨论，958749861
谢谢。。。
